"""SQLite persistence for daily snapshots, reviews, positions and accounts.

Split by domain into submodules; every public and private top-level name is
re-exported here so ``from market_desk.db import X`` and ``market_desk.db.X``
keep working. ``DB_PATH`` / ``DATA_DIR`` live on this package and are read at
connect time, so patching them here redirects every store.
"""

from market_desk.config import DATA_DIR, DB_PATH
from market_desk.db.core import (  # noqa: F401
    _connect,
    _table_cols,
)
from market_desk.db.schema import (  # noqa: F401
    _migrate_signals_owner_user,
    init_db,
    _ensure_ma_fan_tables,
    _ensure_backtest_tables,
    _ensure_auth_and_user_scope,
    _migrate_watchlist_user_scope,
    _migrate_favorite_boards_user_scope,
)
from market_desk.db.ma_fan_store import (  # noqa: F401
    save_ma_fan_day,
    load_ma_fan_day,
    list_ma_fan_dates,
)
from market_desk.db.users import (  # noqa: F401
    user_count,
    create_user,
    update_user_serverchan,
    set_user_serverchan_allowed,
    list_serverchan_recipients,
    get_user_by_username,
    get_user_by_id,
    list_users,
    approve_user,
    reject_user,
    update_user_password,
    delete_user,
    count_active_admins,
    create_session,
    delete_session,
    touch_session,
    get_session_user,
    load_user_setting,
    save_user_setting,
)
from market_desk.db.market import (  # noqa: F401
    save_daily,
    _BREADTH_FIELDS,
    _breadth_span,
    _breadth_fields_degraded,
    _has_nonzero_breadth,
    _has_good_breadth,
    sanitize_daily_row,
    load_daily,
    save_auction,
    load_auction,
    save_board_daily,
    save_fund_flow_daily,
    list_fund_flow_dates,
    load_fund_flow_for_dates,
    load_board_hist_map,
    load_board_rows_for_date,
)
from market_desk.db.reputation import (  # noqa: F401
    upsert_theme_reputation,
    set_theme_manual_adj,
    bump_theme_trade_adj,
    upsert_stock_reputation,
    load_stock_reputation_one,
    load_theme_reputation,
    record_theme_day_outcome,
    load_theme_day_outcomes,
    load_theme_outcomes_for_theme,
    list_theme_outcome_keys,
)
from market_desk.db.positions import (  # noqa: F401
    _POS_SELECT,
    _backfill_position_lots,
    _insert_position_lot,
    _fifo_trim_lots,
    load_lots_for_positions,
    add_exec_diary,
    load_exec_diary,
    load_recent_buy_diary,
    _position_item,
    touch_position_peaks,
    add_position,
    trim_position,
    sync_position_buy_fill,
    sync_position_sell_fill,
    delete_position,
    purge_stale_closed_positions,
    load_positions,
    load_all_book_codes,
    position_buy_day,
    is_t1_locked,
)
from market_desk.db.signals import (  # noqa: F401
    upsert_signal,
    load_signal,
    _SIGNAL_SELECT,
    _decode_signal_rows,
    filter_signals_for_viewer,
    load_signals,
    load_signals_for_code,
    load_signals_for_date,
    find_signal,
    sync_sell_fill_from_trim,
    list_signal_trade_dates,
    purge_sentinel_signal_dates,
    load_unscored_signals,
    mark_signal_outcome,
    update_signal_meta,
    upsert_signal_user_meta,
    load_signal_user_meta_map,
    apply_signal_user_meta,
    save_review_digest,
    load_review_digests,
    delete_signal,
)
from market_desk.db.state import (  # noqa: F401
    load_setting,
    save_setting,
    upsert_session_segment,
    load_session_segments,
    add_mainline_switch,
    delete_mainline_switch,
    try_add_mainline_switch,
    _switch_age_seconds,
    load_mainline_switches,
    load_recent_mainline_switch_stats,
    upsert_trend_override,
    load_trend_overrides,
    delete_trend_override,
)
from market_desk.db.lists import (  # noqa: F401
    add_watchlist,
    load_watchlist,
    delete_watchlist,
    add_favorite_board,
    load_favorite_boards,
    delete_favorite_board,
    delete_favorite_board_by_bk,
    upsert_gap_fade_strike,
    count_gap_fade_strikes,
    load_gap_fade_strike_codes,
    add_stock_blacklist,
    load_stock_blacklist,
    load_blacklist_codes,
    delete_stock_blacklist,
    bump_blacklist_clean_streak,
)
from market_desk.db.backup import (  # noqa: F401
    export_backup_payload,
    export_user_backup_payload,
    import_user_backup_payload,
    import_backup_payload,
)
from market_desk.db.backtest import (  # noqa: F401
    BACKTEST_RUN_KEEP_DEFAULT,
    _FILL_CORE_KEYS,
    save_backtest_run,
    _prune_backtest_runs,
    _backtest_run_row,
    _backtest_fill_row,
    list_backtest_runs,
    get_backtest_run,
    delete_backtest_run,
    clear_backtest_runs,
    compare_backtest_runs,
)
